### ISSUE TITLE
Filter values quoted

### ISSUE THREAD

**Issue by jhosteny** [qvantel/jsonapi-client#11]
Thanks for the library!

In https://github.com/qvantel/jsonapi-client/blob/master/src/jsonapi_client/filter.py#L74, the value is being explicitly quoted. This results in double quoted values upon deserialization in crnk (a fork of Katharsis, a Java jsonapi server-side library). Here is the (non-working) filter setup:

```python
filter = Filter(myUuid=uuidStr)
```

If I explicitly set the filter string as below, it works correctly.

```python
filter = Filter("filter[myUuid]={}".format(uuidStr))
```

I don't believe the values should be explicitly quoted. If you agree, I can submit a patch.

**Comment by ajjn** [comment]
Hi,

Yes, you are correct. Also according to http://jsonapi.org/recommendations/ the filter values are not quoted, so please submit a patch and we'll correct it.

Cheers
Antti
