### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by sidpatel13** [qvantel/jsonapi-client#22]
This part of the docs needs to be updated as it's a bit unclear (Happy to put in a PR :) ):
```
s = Session('http://localhost:8080/',
            request_kwargs=dict(auth=HttpBasicAuth('user', 'password'))
```
from requests.auth import HTTPBasicAuth and `HttpBasicAuth` should be `HTTPBasicAuth`

or 

use aiohttp module to import BasicAuth -> https://aiohttp.readthedocs.io/en/v0.16.2/api.html#aiohttp.helpers.BasicAuth

**Comment by ajjn** [comment]
Thank you for reporting! Fixed and will close this issue.
