### ISSUE TITLE
Default value from JSON schema is not use for validate

### ISSUE THREAD

**Issue by sdayu** [qvantel/jsonapi-client#4]
I created a model from JSON schema with default value attribute, I not set the value to the attribute and commit it. I got
```
jsonschema.exceptions.ValidationError: None is not of type 'string'

Failed validating 'type' in schema['properties']['status']:
    {'default': 'unregister', 'title': 'status', 'type': 'string'}
```
Is it better if the model can use the default value from JSON schema?
Thank,

**Comment by tuomas2** [comment]
Implemented desired feature in https://github.com/qvantel/jsonapi-client/commit/79280d6c8a96c97ff6327f876f6c825b713446d4 which is now released in version 0.9.6.
