### ISSUE TITLE
Relationship object when fetched should follow plural naming

### ISSUE THREAD

**Issue by ola-t** [qvantel/jsonapi-client#5]
Thanks for a great client library. If the relationship contains the data, relation object is retched as a singular `object` not `objects` even `self` link is provided

```
        "relationships": {
            "myobjects": {
                "data": [
                    {
                        "type": "object",
                        "id": "123",
                        "links": {
                            "self": "http://localhost:8000/api/objects/123"
                        }
                    },
```

```
self = <jsonapi_client.session.Session object at 0x1087620f0>
url = 'http://localhost:51588/api/object/123'

    def _fetch_json(self, url: str) -> dict:
        """
            Internal use.
    
            Fetch document raw json from server using requests library.
            """
        self.assert_sync()
        import requests
        parsed_url = urlparse(url)
        logger.info('Fetching document from url %s', parsed_url)
        response = requests.get(parsed_url.geturl(), **self._request_kwargs)
        if response.status_code == HttpStatus.OK_200:
            return response.json()
        else:
    
            raise DocumentError(f'Error {response.status_code}: '
                                f'{error_from_response(response)}',
                                errors={'status_code': response.status_code},
>                               response=response)
E           jsonapi_client.exceptions.DocumentError: Error 404: ?
```

`http://localhost:51588/api/object/123` should be plural, as in the case where `data: []` is not loaded, related links all works well

**Comment by tuomas2** [comment]
- Can you point out why should resource type be pluralized automatically by client code?
When I look at the examples at http://jsonapi.org/format/1.0/ all resource types are in plural form in the first place, which seems to be convention when creating JSON APIs.

- According to http://jsonapi.org/format/#document-resource-object-linkage
your relationships.myobjects.data should be array of resource identifier objects ( http://jsonapi.org/format/#document-resource-identifier-objects), which does not support linkage with 'links' key. Can you check that your API properly follows here JSONAPI 1.0?

**Comment by ola-t** [comment]
yes, that is correct, mistake on my side
