### ISSUE TITLE
question: adding params to requests

### ISSUE THREAD

**Issue by matthdsm** [qvantel/jsonapi-client#9]
Hi,

Quick question. Is it possible to add params when doing `session.get()`?
I know it's possible to add these when creating the `session`, but I'd like to add the params during the `get`phase.

Thanks
M

**Comment by ajjn** [comment]
Hi,

Currently, it is not possible to add request parameters at the get phase. But if there is need for this kind of feature, it is possible to add this to the future versions! 

Cheers
Antti

**Comment by matthdsm** [comment]
Hi,

Thanks for the reply. Would be a nice feature to have though, if it's not to much work.
I've fixed the issue by encoding the get params in the url for now.

Thanks again,
Cheers
M
